version:  '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: on-failure
    volumes:
      - "./jenkins_home:/var/jenkins_home"
    ports:
    - "9280:8080"
    - "50000:50000"
